=begin pod

=head1 NAME

DateTime::Location - Provides location and time data primarily for astronomical programs

=head1 SYNOPSIS

=begin code :lang<raku>
$ raku
> use DateTime::Location;
> my $loc = Location.new;
> say $loc.name;
Niceville, FL, USA
> say $loc.location;
lat: ?, lon: ?
=end code

=head1 DESCRIPTION

C<DateTime::Location> is a Work in Progress (WIP)

=head1 See also

=item C<Astro::Almanac>
=item C<Calender>

=head1 AUTHOR

Tom Browder C<tom.browder@cpan.org>

=head1 COPYRIGHT AND LICENSE

E<0x00a9> 2020 Tom Browder

This library is free software; you may redistribute it or modify it under the Artistic License 2.0.

=end pod
