=begin pod

=head1 NAME

DateTime::Location - blah blah blah

=head1 SYNOPSIS

=begin code :lang<raku>

use DateTime::Location;

=end code

=head1 DESCRIPTION

DateTime::Location is ...

=head1 AUTHOR

Tom Browder <tom.browder@gmail.com>

=head1 COPYRIGHT AND LICENSE

Copyright 2020 Tom Browder

This library is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end pod
